# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Deploy to atlassian cloud site
      run: |
        echo Email check: ${{ secrets.FORGE_EMAIL }} ok
        echo Token check: ${{ secrets.FORGE_API_TOKEN }} ok
        ./scripts/build.sh ${{ secrets.FORGE_EMAIL }} ${{ secrets.FORGE_API_TOKEN }}
        # npm run static:build
        # npx forge login -u ${{ secrets.FORGE_EMAIL }} -t ${{ secrets.FORGE_API_TOKEN }} --non-interactive --verbose
        # npx forge deploy
